import { TableConfig, TableColumn } from "../types";
import { Client } from "../types";

export const clientsTableConfig: TableConfig<Client> = {
  title: "Clients",
  columns: [
    // Existing columns (unchanged)
    {
      key: "client_id",
      label: "Client ID",
      type: "text",
      description: "Unique client identifier",
    },
    {
      key: "status",
      label: "Status",
      type: "text",
      description: "Current lifecycle status",
    },
    {
      key: "id",
      label: "ID",
      type: "integer",
      description: "Internal numeric ID",
    },
    {
      key: "CSM Name",
      label: "CSM Name",
      type: "text",
      description: "Assigned customer success manager",
    },
    {
      key: "total_usage",
      label: "Total Usage",
      type: "integer",
      description: "Cumulative usage count",
    },
    {
      key: "inbound_calls",
      label: "Inbound Calls",
      type: "integer",
      description: "Total inbound calls",
    },
    {
      key: "new_reviews",
      label: "New Reviews",
      type: "integer",
      description: "Reviews received recently",
    },
    {
      key: "new_website_leads",
      label: "New Website Leads",
      type: "integer",
      description: "Leads captured on site",
    },
    {
      key: "created_at",
      label: "Created At",
      type: "timestamp",
      description: "Record creation date",
    },
    {
      key: "started_on",
      label: "Started On",
      type: "timestamp",
      description: "Service start date",
    },
    {
      key: "churned_on",
      label: "Churned On",
      type: "timestamp",
      description: "Churn date if applicable",
    },
    {
      key: "form_complete_time",
      label: "Form Complete Time",
      type: "timestamp",
      description: "Time when onboarding form was completed",
    },
    {
      key: "onboarding_call_time",
      label: "Onboarding Call Time",
      type: "timestamp",
      description: "Scheduled onboarding call time",
    },
    {
      key: "launch_call_time",
      label: "Launch Call Time",
      type: "timestamp",
      description: "Scheduled launch call time",
    },
    {
      key: "last_meaningful_activity_time",
      label: "Last Activity Time",
      type: "timestamp",
      description: "Most recent meaningful client action",
    },
    {
      key: "minutes_to_100_usage",
      label: "Minutes to 100 Usage",
      type: "number",
      description: "Time to reach first 100 usage units",
    },
    {
      key: "minutes_to_first_value",
      label: "Minutes to First Value",
      type: "number",
      description: "Time to first meaningful value",
    },
    // Additional requested columns; will show N/A until backend populates
    {
      key: "Company Name",
      label: "Company Name",
      type: "text",
      description: "Business name",
    },
    {
      key: "Name",
      label: "Name",
      type: "text",
      description: "Primary contact name",
    },
    {
      key: "Closer",
      label: "Closer",
      type: "text",
      description: "Sales closer",
    },
    {
      key: "Contact ID",
      label: "Contact ID",
      type: "text",
      description: "CRM contact identifier",
    },
    {
      key: "Location ID",
      label: "Location ID",
      type: "text",
      description: "CRM location identifier",
    },
    {
      key: "Website Link",
      label: "Website Link",
      type: "text",
      description: "Client website URL",
    },
    {
      key: "Phone Number",
      label: "Phone Number",
      type: "text",
      description: "Primary phone",
    },
    {
      key: "E-mail",
      label: "E-mail",
      type: "text",
      description: "Primary email",
    },
    {
      key: "Stripe Customer ID",
      label: "Stripe Customer ID",
      type: "text",
      description: "Stripe customer reference",
    },
    {
      key: "Time Enrolled",
      label: "Time Enrolled",
      type: "timestamp",
      description: "Enrollment timestamp",
    },
    {
      key: "Cancellation Reason",
      label: "Cancellation Reason",
      type: "text",
      description: "Stated reason for cancel",
    },
    {
      key: "Site Done",
      label: "Site Done",
      type: "text",
      description: "Website delivery status",
    },
    {
      key: "Delivery Person",
      label: "Delivery Person",
      type: "text",
      description: "Assigned delivery owner",
    },
    {
      key: "Cancellation Notes",
      label: "Cancellation Notes",
      type: "text",
      description: "Additional cancellation notes",
    },
    {
      key: "AI Content Created",
      label: "AI Content Created",
      type: "text",
      description: "AI content status",
    },
    {
      key: "A2P",
      label: "A2P",
      type: "text",
      description: "A2P registration status",
    },
    {
      key: "Referrer",
      label: "Referrer",
      type: "text",
      description: "Lead source referrer",
    },
  ],
  data: [],
  showTotals: false,
};
